### ISSUE TITLE
请问如何将反射dll的参数传入

### ISSUE THREAD

**Issue by H4de5-7** [timwhitez/Doge-RL#1]
师傅，请问如何将反射dll的参数传入，目前想用go写一个反射dll的注入，有参数的时候应该怎么处理呢。

**Comment by timwhitez** [comment]
1. 这个项目针对的是未被patch过的反射dll的加载，cs的反射dll patch了头部直接执行就行
2. 对于传输参数，可以将参数的指针传输至rdi函数内，然后进行处理syscall(ptr,arg)这种形式，在rdi函数里接收后传给dllmain

**Comment by H4de5-7** [comment]
谢谢师傅的解答，不过我经过测试，发现cna或者dllinject这些用户自己传入的反射型dll是没有被patch过直接下发的，但是网上也找不到相关的资料，师傅有了解过吗

**Comment by H4de5-7** [comment]
不是特别懂怎么把参数的指针传输到rdi函数内。。二进制太菜了，师傅要是有空的话可以指教一下吗

**Comment by H4de5-7** [comment]
莫事了，谢谢师傅，已解决。
